### ISSUE TITLE
"ImportError: cannot import name 'just_fix_windows_console' from 'colorama'" after updating to latest version

### ISSUE THREAD

**Issue by Jdbaii** [AlexFlipnote/GiveMeBadge#97]
Updated the script to latest version, it no longer runs. Did run the pip install command again, to no avail.
```
Traceback (most recent call last):
  File "/home/givemebadge/GiveMeBadge/index.py", line 6, in <module>
    from colorama import Fore, Style, just_fix_windows_console
ImportError: cannot import name 'just_fix_windows_console' from 'colorama' (/usr/lib/python3/dist-packages/colorama/__init__.py)

```

**Comment by AlexFlipnote** [comment]
Huh, seems like they might have removed it then. I will look into it when I have time.

**Comment by AlexFlipnote** [comment]
I updated my colorama to latest (0.4.6) and it is still there
![image](https://github.com/AlexFlipnote/GiveMeBadge/assets/19587382/e9450360-23ac-4157-ab3c-0feaca88bd31)

**Comment by Kasherpete** [comment]
Hey @AlexFlipnote this is still an issue, and I can confirm it works on 0.4.6. Can you just edit the requirements.txt file to include this instead?
```
discord.py
requests
colorama==0.4.6
```
Specifying the version in your requirements file is generally good practice for Python too. Thanks!

**Comment by AlexFlipnote** [comment]
> Hey @AlexFlipnote this is still an issue, and I can confirm it works on 0.4.6. Can you just edit the requirements.txt file to include this instead?
> 
> ```
> discord.py
> requests
> colorama==0.4.6
> ```
> 
> Specifying the version in your requirements file is generally good practice for Python too. Thanks!

Hi there, sory for not replying. Sure I can fix that!
